import { React, useState, useEffect, useContext } from 'react';
import styles from './History.module.css';
import Skeleton from '@mui/material/Skeleton';
import WithAuthHOC from '../../utils/HOC/withAuthHOC';
import axios from '../../utils/axios';
import { AuthContext } from '../../utils/AuthContext';
import EventNoteIcon from '@mui/icons-material/EventNote';
import DescriptionIcon from '@mui/icons-material/Description';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import DownloadIcon from '@mui/icons-material/Download';
import html2pdf from 'html2pdf.js'; // PDF Generate karne ke liye

const History = () => {
  const [data, setData] = useState([]);
  const [loader, setLoader] = useState(false);

  const { userInfo } = useContext(AuthContext);

  useEffect(() => {
    const fetchUserData = async () => {
      setLoader(true);
      try {
        const results = await axios.get(`/api/resume/get/${userInfo._id}`);
        setData(results.data.resumes);
      } catch (err) {
        console.log(err);
        alert("Error fetching history data. Please try again later.");
      } finally {
        setLoader(false);
      }
    }
    fetchUserData();
  }, []);

  // PDF Download Logic
  const handleDownloadPDF = (item) => {
    const element = document.createElement('div');
    // PDF ke andar ka layout kaisa dikhega (HTML format)
    element.innerHTML = `
        <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b;">
            <div style="text-align: center; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 30px;">
                <h1 style="color: #2563eb; margin: 0; font-size: 32px;">Smart Resume AI Report</h1>
                <p style="color: #64748b; margin-top: 5px;">Analysis & Screening Feedback</p>
            </div>
            
            <table style="width: 100%; margin-bottom: 30px; font-size: 16px;">
                <tr>
                    <td style="padding: 8px 0; color: #64748b; width: 150px;">Candidate Name:</td>
                    <td style="padding: 8px 0; font-weight: bold; color: #0f172a;">${item.resume_name.replace('.pdf', '')}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #64748b;">Analysis Date:</td>
                    <td style="padding: 8px 0; font-weight: bold; color: #0f172a;">${item.createdAt.slice(0, 10)}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #64748b;">Match Score:</td>
                    <td style="padding: 8px 0;">
                        <span style="background: #dcfce7; color: #166534; padding: 4px 12px; border-radius: 20px; font-weight: bold; font-size: 18px;">
                            ${item.score}% Match
                        </span>
                    </td>
                </tr>
            </table>

            <div style="background: #f8fafc; padding: 25px; border-radius: 12px; border: 1px solid #e2e8f0;">
                <h3 style="color: #334155; margin-top: 0; font-size: 18px; text-transform: uppercase; letter-spacing: 1px;">Detailed AI Feedback</h3>
                <p style="line-height: 1.8; color: #334155; font-size: 15px; margin-bottom: 0;">
                    ${item.feedback.replace(/\n/g, '<br/>')}
                </p>
            </div>
            
            <div style="margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px;">
                <p>Generated by MERN Resume AI System</p>
            </div>
        </div>
    `;

    const opt = {
        margin: 0,
        filename: `${item.resume_name.replace('.pdf', '')}_Report.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save();
  };

  return (
    <div className={styles.History}>
      <div className={styles.pageHeader}>
        <h1 className={styles.pageTitle}>Analysis History</h1>
        <p className={styles.pageSubtitle}>Review your past resume screenings and AI feedback</p>
      </div>

      <div className={styles.HistoryCardBlock}>
        {loader && (
          Array.from(new Array(6)).map((_, index) => (
            <Skeleton key={index} variant="rectangular" sx={{ borderRadius: "24px" }} width="100%" height={260} />
          ))
        )}

        {!loader && data.length === 0 && (
           <div className={styles.noData}>No history found. Start analyzing resumes!</div>
        )}

        {!loader && data.map((item) => {
          return (
            <div key={item._id} className={styles.HistoryCard}>
              <div className={styles.cardHeader}>
                <div className={styles.scoreBlock}>
                  <AutoAwesomeIcon sx={{ color: "#a855f7", fontSize: 20 }} />
                  <span className={styles.cardPercentage}>{item.score}%</span>
                  <span className={styles.matchText}>Match</span>
                </div>
                <div className={styles.dateBlock}>
                  <EventNoteIcon sx={{ fontSize: 16, color: "#94a3b8" }} />
                  <span>{item.createdAt.slice(0, 10)}</span>
                </div>
              </div>

              <div className={styles.cardBody}>
                <div className={styles.resumeName}>
                  <DescriptionIcon sx={{ fontSize: 18, color: "#3b82f6" }} />
                  <span>{item.resume_name}</span>
                </div>
                
                <div className={styles.feedbackSection}>
                  <h4>AI Feedback</h4>
                  {/* Yahan par ab scroll aayega, data hide nahi hoga */}
                  <p>{item.feedback}</p>
                </div>

                {/* PDF Download Button */}
                <button 
                  className={styles.downloadBtn} 
                  onClick={() => handleDownloadPDF(item)}
                >
                  <DownloadIcon sx={{ fontSize: 20 }} />
                  Download PDF Report
                </button>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

export default WithAuthHOC(History);